import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Regex',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={cn(
                    inter.className,
                    'bg-background flex flex-col gap-4',
                )}>
                <div className="grid place-items-center">
                    <Header />
                </div>
                <main>{children}</main>
            </body>
        </html>
    );
}
